// This file is auto-generated by @hey-api/openapi-ts

export const sDeck = {
    type: 'object',
    properties: {
        deck_id: {
            type: 'string',
            example: '3p40paa87x90'
        },
        success: {
            type: 'boolean',
            example: true
        },
        shuffled: {
            type: 'boolean',
            example: true
        },
        remaining: {
            type: 'integer',
            format: 'int32',
            example: 52
        }
    }
} as const;

export const sDrawnCards = {
    type: 'object',
    properties: {
        success: {
            type: 'boolean'
        },
        deck_id: {
            type: 'string'
        },
        cards: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/Card'
            }
        },
        remaining: {
            $ref: '#/components/schemas/Remaining',
            example: 30
        },
        piles: {
            $ref: '#/components/schemas/Piles'
        }
    }
} as const;

export const sCard = {
    type: 'object',
    properties: {
        code: {
            type: 'string',
            example: 'AS'
        },
        image: {
            type: 'string',
            format: 'url',
            example: 'https://deckofcardsapi.com/static/img/AS.png'
        },
        images: {
            type: 'object',
            properties: {
                svg: {
                    type: 'string',
                    format: 'url'
                },
                png: {
                    type: 'string',
                    format: 'url'
                }
            }
        },
        value: {
            type: 'string',
            example: 'ACE'
        },
        suit: {
            type: 'string',
            example: 'SPADES',
            enum: [
                'SPADES',
                'CLUBS',
                'HEARTS',
                'DIAMONDS'
            ]
        }
    }
} as const;

export const sCardCodes = {
    type: 'string',
    example: 'AS,2S'
} as const;

export const sPileResult = {
    type: 'object',
    properties: {
        success: {
            type: 'boolean'
        },
        deck_id: {
            type: 'string'
        },
        shuffled: {
            type: 'boolean'
        },
        remaining: {
            $ref: '#/components/schemas/Remaining'
        },
        piles: {
            $ref: '#/components/schemas/Piles'
        }
    }
} as const;

export const sPile = {
    type: 'object',
    properties: {
        remaining: {
            $ref: '#/components/schemas/Remaining'
        },
        cards: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/Card'
            }
        }
    }
} as const;

export const sPiles = {
    type: 'object',
    additionalProperties: {
        $ref: '#/components/schemas/Pile'
    }
} as const;

export const sRemaining = {
    oneOf: [
        {
            type: 'integer',
            format: 'int32'
        },
        {
            type: 'string'
        }
    ],
    example: 52
} as const;
