// This file is auto-generated by @hey-api/openapi-ts

export const sDeck = {
    type: 'object',
    required: [
        'success',
        'deck_id',
        'shuffled',
        'remaining'
    ],
    properties: {
        success: {
            type: 'boolean',
            enum: [
                true
            ]
        },
        deck_id: {
            type: 'string',
            example: '3p40paa87x90'
        },
        shuffled: {
            type: 'boolean',
            example: true
        },
        remaining: {
            type: 'integer',
            format: 'int32',
            example: 52
        }
    }
} as const;

export const sDeckDrawResult = {
    type: 'object',
    required: [
        'success',
        'deck_id',
        'cards',
        'remaining'
    ],
    properties: {
        success: {
            type: 'boolean',
            enum: [
                true
            ]
        },
        deck_id: {
            type: 'string'
        },
        cards: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/Card'
            }
        },
        remaining: {
            $ref: '#/components/schemas/Remaining',
            example: 30
        }
    }
} as const;

export const sPileDrawResult = {
    type: 'object',
    required: [
        'success',
        'deck_id',
        'cards',
        'piles'
    ],
    properties: {
        success: {
            type: 'boolean',
            enum: [
                true
            ]
        },
        deck_id: {
            type: 'string'
        },
        cards: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/Card'
            }
        },
        piles: {
            $ref: '#/components/schemas/Piles'
        }
    }
} as const;

export const sCard = {
    type: 'object',
    required: [
        'code',
        'image',
        'value',
        'suit'
    ],
    properties: {
        code: {
            type: 'string',
            example: 'AS'
        },
        image: {
            type: 'string',
            format: 'url',
            example: 'https://deckofcardsapi.com/static/img/AS.png'
        },
        images: {
            type: 'object',
            properties: {
                svg: {
                    type: 'string',
                    format: 'url'
                },
                png: {
                    type: 'string',
                    format: 'url'
                }
            }
        },
        value: {
            type: 'string',
            example: 'ACE'
        },
        suit: {
            type: 'string',
            example: 'SPADES',
            enum: [
                'SPADES',
                'CLUBS',
                'HEARTS',
                'DIAMONDS'
            ]
        }
    }
} as const;

export const sCardCodes = {
    type: 'string',
    example: 'AS,2S'
} as const;

export const sReturnToDeckResult = {
    type: 'object',
    required: [
        'success',
        'deck_id',
        'remaining'
    ],
    properties: {
        success: {
            type: 'boolean',
            enum: [
                true
            ]
        },
        deck_id: {
            type: 'string'
        },
        shuffled: {
            type: 'boolean'
        },
        remaining: {
            $ref: '#/components/schemas/Remaining'
        }
    }
} as const;

export const sPileOperationResult = {
    type: 'object',
    required: [
        'success',
        'deck_id',
        'remaining',
        'piles'
    ],
    properties: {
        success: {
            type: 'boolean',
            enum: [
                true
            ]
        },
        deck_id: {
            type: 'string'
        },
        shuffled: {
            type: 'boolean'
        },
        remaining: {
            $ref: '#/components/schemas/Remaining'
        },
        piles: {
            $ref: '#/components/schemas/Piles'
        }
    }
} as const;

export const sPile = {
    type: 'object',
    required: [
        'remaining'
    ],
    properties: {
        remaining: {
            $ref: '#/components/schemas/Remaining'
        },
        cards: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/Card'
            }
        }
    }
} as const;

export const sPiles = {
    type: 'object',
    additionalProperties: {
        $ref: '#/components/schemas/Pile'
    }
} as const;

export const sRemaining = {
    oneOf: [
        {
            type: 'integer',
            format: 'int32'
        },
        {
            type: 'string'
        }
    ],
    example: 52
} as const;

export const sErrorResponse = {
    type: 'object',
    required: [
        'success',
        'error'
    ],
    properties: {
        success: {
            type: 'boolean',
            enum: [
                false
            ]
        },
        error: {
            type: 'string',
            example: 'Not enough cards remaining to draw 1 additional'
        }
    }
} as const;

export const sDeckResponse = {
    oneOf: [
        {
            $ref: '#/components/schemas/Deck'
        },
        {
            $ref: '#/components/schemas/ErrorResponse'
        }
    ]
} as const;

export const sDeckDrawResponse = {
    oneOf: [
        {
            $ref: '#/components/schemas/DeckDrawResult'
        },
        {
            $ref: '#/components/schemas/ErrorResponse'
        }
    ]
} as const;

export const sReturnToDeckResponse = {
    oneOf: [
        {
            $ref: '#/components/schemas/ReturnToDeckResult'
        },
        {
            $ref: '#/components/schemas/ErrorResponse'
        }
    ]
} as const;

export const sPileOperationResponse = {
    oneOf: [
        {
            $ref: '#/components/schemas/PileOperationResult'
        },
        {
            $ref: '#/components/schemas/ErrorResponse'
        }
    ]
} as const;

export const sPileDrawResponse = {
    oneOf: [
        {
            $ref: '#/components/schemas/PileDrawResult'
        },
        {
            $ref: '#/components/schemas/ErrorResponse'
        }
    ]
} as const;
