// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { tAddCardsToPileRequest, tAddCardsToPileResponse, tDrawCardsExistingDeckRequest, tDrawCardsExistingDeckResponse, tDrawCardsNewDeckRequest, tDrawCardsNewDeckResponse, tDrawFromDeckBottomRequest, tDrawFromDeckBottomResponse, tDrawFromDeckRandomRequest, tDrawFromDeckRandomResponse, tDrawFromPileRequest, tDrawFromPileResponse, tGetShuffledDeckRequest, tGetShuffledDeckResponse, tGetUnshuffledDeckRequest, tGetUnshuffledDeckResponse, tListPileRequest, tListPileResponse, tReshuffleDeckRequest, tReshuffleDeckResponse, tReturnCardsToDeckRequest, tReturnCardsToDeckResponse, tReturnCardsToPileRequest, tReturnCardsToPileResponse, tShufflePileRequest, tShufflePileResponse } from './types.gen';
import { zAddCardsToPileData, zAddCardsToPileResponse, zDrawCardsExistingDeckData, zDrawCardsExistingDeckResponse, zDrawCardsNewDeckData, zDrawCardsNewDeckResponse, zDrawFromDeckBottomData, zDrawFromDeckBottomResponse, zDrawFromDeckRandomData, zDrawFromDeckRandomResponse, zDrawFromPileData, zDrawFromPileResponse, zGetShuffledDeckData, zGetShuffledDeckResponse, zGetUnshuffledDeckData, zGetUnshuffledDeckResponse, zListPileData, zListPileResponse, zReshuffleDeckData, zReshuffleDeckResponse, zReturnCardsToDeckData, zReturnCardsToDeckResponse, zReturnCardsToPileData, zReturnCardsToPileResponse, zShufflePileData, zShufflePileResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Retrieves new deck(s) of unshuffled cards.
 */
export const getUnshuffledDeck = <ThrowOnError extends boolean = false>(options?: Options<tGetUnshuffledDeckRequest, ThrowOnError>) => (options?.client ?? client).get<tGetUnshuffledDeckResponse, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetUnshuffledDeckData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zGetUnshuffledDeckResponse.parseAsync(data),
    url: '/deck/new/',
    ...options
});

/**
 * Retrieves new deck(s) of shuffled cards.
 */
export const getShuffledDeck = <ThrowOnError extends boolean = false>(options?: Options<tGetShuffledDeckRequest, ThrowOnError>) => (options?.client ?? client).get<tGetShuffledDeckResponse, unknown, ThrowOnError>({
    requestValidator: async (data) => await zGetShuffledDeckData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zGetShuffledDeckResponse.parseAsync(data),
    url: '/deck/new/shuffle/',
    ...options
});

/**
 * Draws cards from deck
 */
export const drawCardsExistingDeck = <ThrowOnError extends boolean = false>(options: Options<tDrawCardsExistingDeckRequest, ThrowOnError>) => (options.client ?? client).get<tDrawCardsExistingDeckResponse, unknown, ThrowOnError>({
    requestValidator: async (data) => await zDrawCardsExistingDeckData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zDrawCardsExistingDeckResponse.parseAsync(data),
    url: '/deck/{deck_id}/draw/',
    ...options
});

/**
 * Retrieves new deck and draws given number of cards
 */
export const drawCardsNewDeck = <ThrowOnError extends boolean = false>(options?: Options<tDrawCardsNewDeckRequest, ThrowOnError>) => (options?.client ?? client).get<tDrawCardsNewDeckResponse, unknown, ThrowOnError>({
    requestValidator: async (data) => await zDrawCardsNewDeckData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zDrawCardsNewDeckResponse.parseAsync(data),
    url: '/deck/new/draw/',
    ...options
});

/**
 * Draw from bottom of deck
 */
export const drawFromDeckBottom = <ThrowOnError extends boolean = false>(options: Options<tDrawFromDeckBottomRequest, ThrowOnError>) => (options.client ?? client).get<tDrawFromDeckBottomResponse, unknown, ThrowOnError>({
    requestValidator: async (data) => await zDrawFromDeckBottomData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zDrawFromDeckBottomResponse.parseAsync(data),
    url: '/deck/{deck_id}/draw/bottom/',
    ...options
});

/**
 * Draw randomly from deck
 */
export const drawFromDeckRandom = <ThrowOnError extends boolean = false>(options: Options<tDrawFromDeckRandomRequest, ThrowOnError>) => (options.client ?? client).get<tDrawFromDeckRandomResponse, unknown, ThrowOnError>({
    requestValidator: async (data) => await zDrawFromDeckRandomData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zDrawFromDeckRandomResponse.parseAsync(data),
    url: '/deck/{deck_id}/draw/random/',
    ...options
});

/**
 * Reshuffle an existing deck
 */
export const reshuffleDeck = <ThrowOnError extends boolean = false>(options: Options<tReshuffleDeckRequest, ThrowOnError>) => (options.client ?? client).get<tReshuffleDeckResponse, unknown, ThrowOnError>({
    requestValidator: async (data) => await zReshuffleDeckData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zReshuffleDeckResponse.parseAsync(data),
    url: '/deck/{deck_id}/shuffle/',
    ...options
});

/**
 * Return cards to deck
 */
export const returnCardsToDeck = <ThrowOnError extends boolean = false>(options: Options<tReturnCardsToDeckRequest, ThrowOnError>) => (options.client ?? client).get<tReturnCardsToDeckResponse, unknown, ThrowOnError>({
    requestValidator: async (data) => await zReturnCardsToDeckData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zReturnCardsToDeckResponse.parseAsync(data),
    url: '/deck/{deck_id}/return/',
    ...options
});

/**
 * Add cards to a new or existing pile. If pile doesn't exist, it will be created.
 */
export const addCardsToPile = <ThrowOnError extends boolean = false>(options: Options<tAddCardsToPileRequest, ThrowOnError>) => (options.client ?? client).get<tAddCardsToPileResponse, unknown, ThrowOnError>({
    requestValidator: async (data) => await zAddCardsToPileData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zAddCardsToPileResponse.parseAsync(data),
    url: '/deck/{deck_id}/pile/{pile_id}/add/',
    ...options
});

/**
 * Shuffle a specified pile.
 */
export const shufflePile = <ThrowOnError extends boolean = false>(options: Options<tShufflePileRequest, ThrowOnError>) => (options.client ?? client).get<tShufflePileResponse, unknown, ThrowOnError>({
    requestValidator: async (data) => await zShufflePileData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zShufflePileResponse.parseAsync(data),
    url: '/deck/{deck_id}/pile/{pile_id}/shuffle/',
    ...options
});

/**
 * List contents of a pile
 */
export const listPile = <ThrowOnError extends boolean = false>(options: Options<tListPileRequest, ThrowOnError>) => (options.client ?? client).get<tListPileResponse, unknown, ThrowOnError>({
    requestValidator: async (data) => await zListPileData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zListPileResponse.parseAsync(data),
    url: '/deck/{deck_id}/pile/{pile_id}/list/',
    ...options
});

/**
 * Draw from pile
 */
export const drawFromPile = <ThrowOnError extends boolean = false>(options: Options<tDrawFromPileRequest, ThrowOnError>) => (options.client ?? client).get<tDrawFromPileResponse, unknown, ThrowOnError>({
    requestValidator: async (data) => await zDrawFromPileData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zDrawFromPileResponse.parseAsync(data),
    url: '/deck/{deck_id}/pile/{pile_id}/draw/',
    ...options
});

/**
 * Return cards to deck
 */
export const returnCardsToPile = <ThrowOnError extends boolean = false>(options: Options<tReturnCardsToPileRequest, ThrowOnError>) => (options.client ?? client).get<tReturnCardsToPileResponse, unknown, ThrowOnError>({
    requestValidator: async (data) => await zReturnCardsToPileData.parseAsync(data),
    responseType: 'json',
    responseValidator: async (data) => await zReturnCardsToPileResponse.parseAsync(data),
    url: '/deck/{deck_id}/pile/{pile_id}/return/',
    ...options
});
