// This file is auto-generated by @hey-api/openapi-ts

export type clientOptions = {
    baseURL: 'https://deckofcardsapi.com/api' | 'http://localhost:6789' | (string & {});
};

export type tDeck = {
    deck_id?: string;
    success?: boolean;
    shuffled?: boolean;
    remaining?: number;
};

export type tDrawnCards = {
    success?: boolean;
    deck_id?: string;
    cards?: Array<tCard>;
    remaining?: number;
};

export type tCard = {
    code?: string;
    image?: string;
    images?: {
        svg?: string;
        png?: string;
    };
    value?: string;
    suit?: 'SPADES' | 'CLUBS' | 'HEARTS' | 'DIAMONDS';
};

export type tCardCodes = Array<string>;

export type tPileResult = {
    success?: boolean;
    deck_id?: string;
    remaining?: number;
    piles?: {
        [key: string]: unknown;
    };
};

export type tPile = {
    remaining?: number;
};

export type tGetUnshuffledDeckRequest = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of decks to retrieve
         */
        deck_count?: string;
        jokers_enabled?: boolean;
    };
    url: '/deck/new/';
};

export type tGetUnshuffledDeckResponse = {
    /**
     * One or more combined card decks
     */
    200: tDeck;
};

export type getUnshuffledDeckResponse = tGetUnshuffledDeckResponse[keyof tGetUnshuffledDeckResponse];

export type tGetShuffledDeckRequest = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of decks to retrieve
         */
        deck_count?: number;
        cards?: Array<tCardCodes>;
    };
    url: '/deck/new/shuffle/';
};

export type tGetShuffledDeckResponse = {
    /**
     * One or more combined card decks, or a partial deck if cards is specified in query string.
     */
    200: tDeck;
};

export type getShuffledDeckResponse = tGetShuffledDeckResponse[keyof tGetShuffledDeckResponse];

export type tDrawCardsExistingDeckRequest = {
    body?: never;
    path: {
        /**
         * Specified deck to draw from
         */
        deck_id: string;
    };
    query?: {
        /**
         * Number of cards to draw
         */
        count?: number;
    };
    url: '/deck/{deck_id}/draw/';
};

export type tDrawCardsExistingDeckResponse = {
    /**
     * One or more combined card decks
     */
    200: tDrawnCards;
};

export type drawCardsExistingDeckResponse = tDrawCardsExistingDeckResponse[keyof tDrawCardsExistingDeckResponse];

export type tDrawCardsNewDeckRequest = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Number of cards to draw
         */
        count?: number;
    };
    url: '/deck/new/draw/';
};

export type tDrawCardsNewDeckResponse = {
    /**
     * One or more combined card decks
     */
    200: tDrawnCards;
};

export type drawCardsNewDeckResponse = tDrawCardsNewDeckResponse[keyof tDrawCardsNewDeckResponse];

export type tDrawFromDeckBottomRequest = {
    body?: never;
    path: {
        deck_id: string;
    };
    query?: never;
    url: '/deck/{deck_id}/draw/bottom/';
};

export type tDrawFromDeckBottomResponse = {
    /**
     * Drawn cards
     */
    200: tDrawnCards;
};

export type drawFromDeckBottomResponse = tDrawFromDeckBottomResponse[keyof tDrawFromDeckBottomResponse];

export type tDrawFromDeckRandomRequest = {
    body?: never;
    path: {
        deck_id: string;
    };
    query?: never;
    url: '/deck/{deck_id}/draw/random/';
};

export type tDrawFromDeckRandomResponse = {
    /**
     * Drawn cards
     */
    200: tDrawnCards;
};

export type drawFromDeckRandomResponse = tDrawFromDeckRandomResponse[keyof tDrawFromDeckRandomResponse];

export type tReshuffleDeckRequest = {
    body?: never;
    path: {
        deck_id: string;
    };
    query?: {
        remaining?: boolean;
    };
    url: '/deck/{deck_id}/shuffle/';
};

export type tReshuffleDeckResponse = {
    /**
     * One or more combined card decks
     */
    200: tDeck;
};

export type reshuffleDeckResponse = tReshuffleDeckResponse[keyof tReshuffleDeckResponse];

export type tReturnCardsToDeckRequest = {
    body?: never;
    path: {
        deck_id: string;
    };
    query: {
        cards: tCardCodes;
    };
    url: '/deck/{deck_id}/return/';
};

export type tReturnCardsToDeckResponse = {
    /**
     * Result of adding to card pile
     */
    200: tPileResult;
};

export type returnCardsToDeckResponse = tReturnCardsToDeckResponse[keyof tReturnCardsToDeckResponse];

export type tAddCardsToPileRequest = {
    body?: never;
    path: {
        deck_id: string;
        pile_id: string;
    };
    query: {
        cards: tCardCodes;
    };
    url: '/deck/{deck_id}/pile/{pile_id}/add/';
};

export type tAddCardsToPileResponse = {
    /**
     * Result of adding to card pile
     */
    200: tPileResult;
};

export type addCardsToPileResponse = tAddCardsToPileResponse[keyof tAddCardsToPileResponse];

export type tShufflePileRequest = {
    body?: never;
    path: {
        deck_id: string;
        pile_id: string;
    };
    query?: never;
    url: '/deck/{deck_id}/pile/{pile_id}/shuffle/';
};

export type tShufflePileResponse = {
    /**
     * Result of adding to card pile
     */
    200: tPileResult;
};

export type shufflePileResponse = tShufflePileResponse[keyof tShufflePileResponse];

export type tListPileRequest = {
    body?: never;
    path: {
        deck_id: string;
        pile_id: string;
    };
    query?: never;
    url: '/deck/{deck_id}/pile/{pile_id}/list/';
};

export type tListPileResponse = {
    /**
     * Result of adding to card pile
     */
    200: tPileResult;
};

export type listPileResponse = tListPileResponse[keyof tListPileResponse];

export type tDrawFromPileRequest = {
    body?: never;
    path: {
        deck_id: string;
        pile_id: string;
    };
    query?: {
        count?: number;
        cards?: Array<tCardCodes>;
    };
    url: '/deck/{deck_id}/pile/{pile_id}/draw/';
};

export type tDrawFromPileResponse = {
    /**
     * Drawn cards from pile
     */
    200: tDrawnCards;
};

export type drawFromPileResponse = tDrawFromPileResponse[keyof tDrawFromPileResponse];

export type tReturnCardsToPileRequest = {
    body?: never;
    path: {
        deck_id: string;
        pile_id: string;
    };
    query: {
        cards: tCardCodes;
    };
    url: '/deck/{deck_id}/pile/{pile_id}/return/';
};

export type tReturnCardsToPileResponse = {
    /**
     * Result of adding to card pile
     */
    200: tPileResult;
};

export type returnCardsToPileResponse = tReturnCardsToPileResponse[keyof tReturnCardsToPileResponse];
