// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zDeck = z.object({
    success: z.literal(true),
    deck_id: z.string(),
    shuffled: z.boolean(),
    remaining: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

export type zDeck = z.infer<typeof zDeck>;

export const zCard = z.object({
    code: z.string(),
    image: z.string(),
    images: z.object({
        svg: z.string().optional(),
        png: z.string().optional()
    }).optional(),
    value: z.string(),
    suit: z.enum([
        'SPADES',
        'CLUBS',
        'HEARTS',
        'DIAMONDS'
    ])
});

export type zCard = z.infer<typeof zCard>;

/**
 * Comma-separated list of card codes, for example AS,2S
 */
export const zCardCodes = z.string().register(z.globalRegistry, {
    description: 'Comma-separated list of card codes, for example AS,2S'
});

export type zCardCodes = z.infer<typeof zCardCodes>;

export const zRemaining = z.union([
    z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    z.string()
]);

export type zRemaining = z.infer<typeof zRemaining>;

export const zDeckDrawResult = z.object({
    success: z.literal(true),
    deck_id: z.string(),
    cards: z.array(zCard),
    remaining: zRemaining
});

export type zDeckDrawResult = z.infer<typeof zDeckDrawResult>;

export const zReturnToDeckResult = z.object({
    success: z.literal(true),
    deck_id: z.string(),
    shuffled: z.boolean().optional(),
    remaining: zRemaining
});

export type zReturnToDeckResult = z.infer<typeof zReturnToDeckResult>;

export const zPile = z.object({
    remaining: zRemaining,
    cards: z.array(zCard).optional()
});

export type zPile = z.infer<typeof zPile>;

export const zPiles = z.record(z.string(), zPile);

export type zPiles = z.infer<typeof zPiles>;

export const zPileDrawResult = z.object({
    success: z.literal(true),
    deck_id: z.string(),
    cards: z.array(zCard),
    piles: zPiles
});

export type zPileDrawResult = z.infer<typeof zPileDrawResult>;

export const zPileOperationResult = z.object({
    success: z.literal(true),
    deck_id: z.string(),
    shuffled: z.boolean().optional(),
    remaining: zRemaining,
    piles: zPiles
});

export type zPileOperationResult = z.infer<typeof zPileOperationResult>;

export const zErrorResponse = z.object({
    success: z.literal(false),
    error: z.string()
});

export type zErrorResponse = z.infer<typeof zErrorResponse>;

export const zDeckResponse = z.union([
    zDeck,
    zErrorResponse
]);

export type zDeckResponse = z.infer<typeof zDeckResponse>;

export const zDeckDrawResponse = z.union([
    zDeckDrawResult,
    zErrorResponse
]);

export type zDeckDrawResponse = z.infer<typeof zDeckDrawResponse>;

export const zReturnToDeckResponse = z.union([
    zReturnToDeckResult,
    zErrorResponse
]);

export type zReturnToDeckResponse = z.infer<typeof zReturnToDeckResponse>;

export const zPileOperationResponse = z.union([
    zPileOperationResult,
    zErrorResponse
]);

export type zPileOperationResponse = z.infer<typeof zPileOperationResponse>;

export const zPileDrawResponse = z.union([
    zPileDrawResult,
    zErrorResponse
]);

export type zPileDrawResponse = z.infer<typeof zPileDrawResponse>;

export const zGetUnshuffledDeckData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        deck_count: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).register(z.globalRegistry, {
            description: 'Number of decks to retrieve'
        }).optional(),
        jokers_enabled: z.boolean().optional()
    }).optional()
});

export type zgetUnshuffledDeckRequest = z.infer<typeof zGetUnshuffledDeckData>;

/**
 * One or more combined card decks
 */
export const zGetUnshuffledDeckResponse = zDeckResponse;

export type zgetUnshuffledDeckResponse = z.infer<typeof zGetUnshuffledDeckResponse>;

export const zGetShuffledDeckData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        deck_count: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).register(z.globalRegistry, {
            description: 'Number of decks to retrieve'
        }).optional(),
        cards: zCardCodes.optional()
    }).optional()
});

export type zgetShuffledDeckRequest = z.infer<typeof zGetShuffledDeckData>;

/**
 * One or more combined card decks, or a partial deck if cards is specified in query string.
 */
export const zGetShuffledDeckResponse = zDeckResponse;

export type zgetShuffledDeckResponse = z.infer<typeof zGetShuffledDeckResponse>;

export const zDrawCardsExistingDeckData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string().register(z.globalRegistry, {
            description: 'Specified deck to draw from'
        })
    }),
    query: z.object({
        count: z.int().register(z.globalRegistry, {
            description: 'Number of cards to draw'
        }).optional()
    }).optional()
});

export type zdrawCardsExistingDeckRequest = z.infer<typeof zDrawCardsExistingDeckData>;

/**
 * One or more combined card decks
 */
export const zDrawCardsExistingDeckResponse = zDeckDrawResponse;

export type zdrawCardsExistingDeckResponse = z.infer<typeof zDrawCardsExistingDeckResponse>;

export const zDrawCardsNewDeckData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        count: z.int().register(z.globalRegistry, {
            description: 'Number of cards to draw'
        }).optional()
    }).optional()
});

export type zdrawCardsNewDeckRequest = z.infer<typeof zDrawCardsNewDeckData>;

/**
 * One or more combined card decks
 */
export const zDrawCardsNewDeckResponse = zDeckDrawResponse;

export type zdrawCardsNewDeckResponse = z.infer<typeof zDrawCardsNewDeckResponse>;

export const zReshuffleDeckData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string()
    }),
    query: z.object({
        remaining: z.boolean().optional()
    }).optional()
});

export type zreshuffleDeckRequest = z.infer<typeof zReshuffleDeckData>;

/**
 * One or more combined card decks
 */
export const zReshuffleDeckResponse = zDeckResponse;

export type zreshuffleDeckResponse = z.infer<typeof zReshuffleDeckResponse>;

export const zReturnCardsToDeckData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string()
    }),
    query: z.object({
        cards: zCardCodes.optional()
    }).optional()
});

export type zreturnCardsToDeckRequest = z.infer<typeof zReturnCardsToDeckData>;

/**
 * Result of returning cards to the deck
 */
export const zReturnCardsToDeckResponse = zReturnToDeckResponse;

export type zreturnCardsToDeckResponse = z.infer<typeof zReturnCardsToDeckResponse>;

export const zAddCardsToPileData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string(),
        pile_name: z.string()
    }),
    query: z.object({
        cards: zCardCodes
    })
});

export type zaddCardsToPileRequest = z.infer<typeof zAddCardsToPileData>;

/**
 * Result of adding to card pile
 */
export const zAddCardsToPileResponse = zPileOperationResponse;

export type zaddCardsToPileResponse = z.infer<typeof zAddCardsToPileResponse>;

export const zShufflePileData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string(),
        pile_name: z.string()
    }),
    query: z.never().optional()
});

export type zshufflePileRequest = z.infer<typeof zShufflePileData>;

/**
 * Result of shuffling a pile
 */
export const zShufflePileResponse = zPileOperationResponse;

export type zshufflePileResponse = z.infer<typeof zShufflePileResponse>;

export const zListPileData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string(),
        pile_name: z.string()
    }),
    query: z.never().optional()
});

export type zlistPileRequest = z.infer<typeof zListPileData>;

/**
 * Result of listing a pile
 */
export const zListPileResponse = zPileOperationResponse;

export type zlistPileResponse = z.infer<typeof zListPileResponse>;

export const zDrawFromPileData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string(),
        pile_name: z.string()
    }),
    query: z.object({
        count: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
        cards: zCardCodes.optional()
    }).optional()
});

export type zdrawFromPileRequest = z.infer<typeof zDrawFromPileData>;

/**
 * Drawn cards from pile
 */
export const zDrawFromPileResponse = zPileDrawResponse;

export type zdrawFromPileResponse = z.infer<typeof zDrawFromPileResponse>;

export const zDrawFromPileBottomData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string(),
        pile_name: z.string()
    }),
    query: z.object({
        count: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
    }).optional()
});

export type zdrawFromPileBottomRequest = z.infer<typeof zDrawFromPileBottomData>;

/**
 * Drawn cards from the bottom of a pile
 */
export const zDrawFromPileBottomResponse = zPileDrawResponse;

export type zdrawFromPileBottomResponse = z.infer<typeof zDrawFromPileBottomResponse>;

export const zDrawFromPileRandomData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string(),
        pile_name: z.string()
    }),
    query: z.object({
        count: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
    }).optional()
});

export type zdrawFromPileRandomRequest = z.infer<typeof zDrawFromPileRandomData>;

/**
 * Randomly drawn cards from a pile
 */
export const zDrawFromPileRandomResponse = zPileDrawResponse;

export type zdrawFromPileRandomResponse = z.infer<typeof zDrawFromPileRandomResponse>;

export const zReturnCardsToPileData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string(),
        pile_name: z.string()
    }),
    query: z.object({
        cards: zCardCodes.optional()
    }).optional()
});

export type zreturnCardsToPileRequest = z.infer<typeof zReturnCardsToPileData>;

/**
 * Result of returning cards from a pile to the deck
 */
export const zReturnCardsToPileResponse = zPileOperationResponse;

export type zreturnCardsToPileResponse = z.infer<typeof zReturnCardsToPileResponse>;
