// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zDeck = z.object({
    deck_id: z.string().optional(),
    success: z.boolean().optional(),
    shuffled: z.boolean().optional(),
    remaining: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
});

export type zDeck = z.infer<typeof zDeck>;

export const zCard = z.object({
    code: z.string().optional(),
    image: z.string().optional(),
    images: z.object({
        svg: z.string().optional(),
        png: z.string().optional()
    }).optional(),
    value: z.string().optional(),
    suit: z.enum([
        'SPADES',
        'CLUBS',
        'HEARTS',
        'DIAMONDS'
    ]).optional()
});

export type zCard = z.infer<typeof zCard>;

/**
 * Comma-separated list of card codes, for example AS,2S
 */
export const zCardCodes = z.string().register(z.globalRegistry, {
    description: 'Comma-separated list of card codes, for example AS,2S'
});

export type zCardCodes = z.infer<typeof zCardCodes>;

export const zRemaining = z.union([
    z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    z.string()
]);

export type zRemaining = z.infer<typeof zRemaining>;

export const zPile = z.object({
    remaining: zRemaining.optional(),
    cards: z.array(zCard).optional()
});

export type zPile = z.infer<typeof zPile>;

export const zPiles = z.record(z.string(), zPile);

export type zPiles = z.infer<typeof zPiles>;

export const zDrawnCards = z.object({
    success: z.boolean().optional(),
    deck_id: z.string().optional(),
    cards: z.array(zCard).optional(),
    remaining: zRemaining.optional(),
    piles: zPiles.optional()
});

export type zDrawnCards = z.infer<typeof zDrawnCards>;

export const zPileResult = z.object({
    success: z.boolean().optional(),
    deck_id: z.string().optional(),
    shuffled: z.boolean().optional(),
    remaining: zRemaining.optional(),
    piles: zPiles.optional()
});

export type zPileResult = z.infer<typeof zPileResult>;

export const zGetUnshuffledDeckData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        deck_count: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).register(z.globalRegistry, {
            description: 'Number of decks to retrieve'
        }).optional(),
        jokers_enabled: z.boolean().optional()
    }).optional()
});

export type zgetUnshuffledDeckRequest = z.infer<typeof zGetUnshuffledDeckData>;

/**
 * One or more combined card decks
 */
export const zGetUnshuffledDeckResponse = zDeck;

export type zgetUnshuffledDeckResponse = z.infer<typeof zGetUnshuffledDeckResponse>;

export const zGetShuffledDeckData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        deck_count: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).register(z.globalRegistry, {
            description: 'Number of decks to retrieve'
        }).optional(),
        cards: zCardCodes.optional()
    }).optional()
});

export type zgetShuffledDeckRequest = z.infer<typeof zGetShuffledDeckData>;

/**
 * One or more combined card decks, or a partial deck if cards is specified in query string.
 */
export const zGetShuffledDeckResponse = zDeck;

export type zgetShuffledDeckResponse = z.infer<typeof zGetShuffledDeckResponse>;

export const zDrawCardsExistingDeckData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string().register(z.globalRegistry, {
            description: 'Specified deck to draw from'
        })
    }),
    query: z.object({
        count: z.int().register(z.globalRegistry, {
            description: 'Number of cards to draw'
        }).optional()
    }).optional()
});

export type zdrawCardsExistingDeckRequest = z.infer<typeof zDrawCardsExistingDeckData>;

/**
 * One or more combined card decks
 */
export const zDrawCardsExistingDeckResponse = zDrawnCards;

export type zdrawCardsExistingDeckResponse = z.infer<typeof zDrawCardsExistingDeckResponse>;

export const zDrawCardsNewDeckData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        count: z.int().register(z.globalRegistry, {
            description: 'Number of cards to draw'
        }).optional()
    }).optional()
});

export type zdrawCardsNewDeckRequest = z.infer<typeof zDrawCardsNewDeckData>;

/**
 * One or more combined card decks
 */
export const zDrawCardsNewDeckResponse = zDrawnCards;

export type zdrawCardsNewDeckResponse = z.infer<typeof zDrawCardsNewDeckResponse>;

export const zReshuffleDeckData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string()
    }),
    query: z.object({
        remaining: z.boolean().optional()
    }).optional()
});

export type zreshuffleDeckRequest = z.infer<typeof zReshuffleDeckData>;

/**
 * One or more combined card decks
 */
export const zReshuffleDeckResponse = zDeck;

export type zreshuffleDeckResponse = z.infer<typeof zReshuffleDeckResponse>;

export const zReturnCardsToDeckData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string()
    }),
    query: z.object({
        cards: zCardCodes.optional()
    }).optional()
});

export type zreturnCardsToDeckRequest = z.infer<typeof zReturnCardsToDeckData>;

/**
 * Result of adding to card pile
 */
export const zReturnCardsToDeckResponse = zPileResult;

export type zreturnCardsToDeckResponse = z.infer<typeof zReturnCardsToDeckResponse>;

export const zAddCardsToPileData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string(),
        pile_name: z.string()
    }),
    query: z.object({
        cards: zCardCodes
    })
});

export type zaddCardsToPileRequest = z.infer<typeof zAddCardsToPileData>;

/**
 * Result of adding to card pile
 */
export const zAddCardsToPileResponse = zPileResult;

export type zaddCardsToPileResponse = z.infer<typeof zAddCardsToPileResponse>;

export const zShufflePileData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string(),
        pile_name: z.string()
    }),
    query: z.never().optional()
});

export type zshufflePileRequest = z.infer<typeof zShufflePileData>;

/**
 * Result of adding to card pile
 */
export const zShufflePileResponse = zPileResult;

export type zshufflePileResponse = z.infer<typeof zShufflePileResponse>;

export const zListPileData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string(),
        pile_name: z.string()
    }),
    query: z.never().optional()
});

export type zlistPileRequest = z.infer<typeof zListPileData>;

/**
 * Result of adding to card pile
 */
export const zListPileResponse = zPileResult;

export type zlistPileResponse = z.infer<typeof zListPileResponse>;

export const zDrawFromPileData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string(),
        pile_name: z.string()
    }),
    query: z.object({
        count: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional(),
        cards: zCardCodes.optional()
    }).optional()
});

export type zdrawFromPileRequest = z.infer<typeof zDrawFromPileData>;

/**
 * Drawn cards from pile
 */
export const zDrawFromPileResponse = zDrawnCards;

export type zdrawFromPileResponse = z.infer<typeof zDrawFromPileResponse>;

export const zDrawFromPileBottomData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string(),
        pile_name: z.string()
    }),
    query: z.object({
        count: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
    }).optional()
});

export type zdrawFromPileBottomRequest = z.infer<typeof zDrawFromPileBottomData>;

/**
 * Drawn cards from the bottom of a pile
 */
export const zDrawFromPileBottomResponse = zDrawnCards;

export type zdrawFromPileBottomResponse = z.infer<typeof zDrawFromPileBottomResponse>;

export const zDrawFromPileRandomData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string(),
        pile_name: z.string()
    }),
    query: z.object({
        count: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).optional()
    }).optional()
});

export type zdrawFromPileRandomRequest = z.infer<typeof zDrawFromPileRandomData>;

/**
 * Randomly drawn cards from a pile
 */
export const zDrawFromPileRandomResponse = zDrawnCards;

export type zdrawFromPileRandomResponse = z.infer<typeof zDrawFromPileRandomResponse>;

export const zReturnCardsToPileData = z.object({
    body: z.never().optional(),
    path: z.object({
        deck_id: z.string(),
        pile_name: z.string()
    }),
    query: z.object({
        cards: zCardCodes.optional()
    }).optional()
});

export type zreturnCardsToPileRequest = z.infer<typeof zReturnCardsToPileData>;

/**
 * Result of adding to card pile
 */
export const zReturnCardsToPileResponse = zPileResult;

export type zreturnCardsToPileResponse = z.infer<typeof zReturnCardsToPileResponse>;
